import { stringify } from "yaml";
import type { BiltzConfig } from "./schema.js";
import { writeAtomic } from "../utils/fs.js";

export async function writeConfig(path: string, config: BiltzConfig): Promise<void> {
  const yaml = stringify(config, {
    indent: 2,
    defaultKeyType: "PLAIN",
    defaultStringType: "QUOTE_SINGLE",
  });
  await writeAtomic(path, yaml);
}

export async function writeConfigExample(path: string, config: BiltzConfig): Promise<void> {
  const lines: string[] = [
    "# biltz.yml example",
    "# Generated by biltz init",
    "",
    `version: ${config.version}`,
    `spec: '${config.spec}'`,
    `agents: [${config.agents.map((a) => `'${a}'`).join(", ")}]`,
    "",
    "routing:",
    "  easy:",
    `    agent: '${config.routing.easy.agent}'`,
    `    model: '${config.routing.easy.model}'`,
    "  medium:",
    `    agent: '${config.routing.medium.agent}'`,
    `    model: '${config.routing.medium.model}'`,
    "  hard:",
    `    agent: '${config.routing.hard.agent}'`,
    `    model: '${config.routing.hard.model}'`,
    "",
    "options:",
    `  max_parallel: ${config.options.max_parallel}`,
    `  agent_timeout_seconds: ${config.options.agent_timeout_seconds}`,
    `  log_dir: '${config.options.log_dir}'`,
    `  on_failure: '${config.options.on_failure}'`,
    `  poll_interval_ms: ${config.options.poll_interval_ms}`,
    "",
  ];
  await writeAtomic(path, lines.join("\n"));
}
